### PR TITLE
WIP: Remove expired online apps

### PR DESCRIPTION
**Pull request by colinbruce**
[Trello ticket](https://trello.com/c/EGd76BWQ/20-remove-online-applications-after-4-months-of-not-being-used)

If an online-application is completed but the number is not passed to staff within three months the application should be deleted.  The threshold is set to 4 months here to allow some time for delays in processing by the  court.

Before we purged online applications, the online_application table was the single source of truth for unused references.  Now we need to ensure that HWF-XXX-YYY isn’t used in either the
OnlineApplication or Application datasets.

### Task list
- [x] test in branch builder
- [x] code review
- [x] platforms review
- [x] test on demo
- [x] Check with content about adding expiry warning to email/done pages
- [x] get welsh translation for public app
- [ ] test on staging

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 29ee32608454d2980ebafae7422743da4c87e53f
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/ministryofjustice/fr-staffapp

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 29ee32608454d2980ebafae7422743da4c87e53f
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/ministryofjustice/fr-staffapp

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 29ee32608454d2980ebafae7422743da4c87e53f
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/ministryofjustice/fr-staffapp

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 29ee32608454d2980ebafae7422743da4c87e53f
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/ministryofjustice/fr-staffapp

---
This message was auto-generated by https://gitcop.com

**Comment by filipposc5** [comment]
From a platforms perspective, I have usually opted with having a rake task and using  https://github.com/ministryofjustice/cron-formula in the deploy repo because this approach lets you control things like "do i run this on every instance or just on one instance" , as well as logging into a separate file which can then be shipped, as well as not running multiple "services" within the container, and finally you have also 1 centralised place for jobs etc.  

From our discussion you said this is not mission critical so even if it falls off our radar for a few days it's still fine, so in this case I 'd say the use of `whenever` is fine. 👍

**Comment by jsugarman** [comment]
LGTM 👍

**Comment by amn-git** [comment]
This is on hold until a Business decision on what the retention period needs to be. (Refer to the HwF Product Manager).

**Comment by zaparka** [comment]
Stale PR

**Pull request closed without merging**
